services:
  - type: web
    name: nexus-chat-app
    env: node
    plan: free
    buildCommand: cd fullstack-chat-app-master && npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: cd fullstack-chat-app-master/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
